#!/bin/bash
# Test script for DigiDollar Overview Tab transaction tracking

echo "==========================================="
echo "DigiDollar Overview Tab Transaction Test"
echo "==========================================="
echo ""

# Start regtest node
echo "1. Starting regtest node..."
./src/qt/digibyte-qt -regtest -server -rpcuser=test -rpcpassword=test -datadir=/tmp/dd-test-overview &
QT_PID=$!
sleep 10

echo "2. Testing transaction tracking..."
echo "   - Open DigiDollar tab"
echo "   - Navigate to Overview tab"
echo "   - Check initial state: 'No recent DigiDollar transactions'"
echo ""
echo "3. Testing mint transaction..."
echo "   - Go to Mint tab"
echo "   - Mint 100 DD with Tier 1"
echo "   - Check Overview tab for mint transaction"
echo "   - Should show: 🏦 Mint $100.00 Pending"
echo ""
echo "4. Testing confirmation updates..."
echo "   - Mine a block: ./src/digibyte-cli -regtest -rpcuser=test -rpcpassword=test generatetoaddress 1 [address]"
echo "   - Check Overview tab"
echo "   - Should show: 🏦 Mint $100.00 1 conf"
echo ""
echo "5. Testing send transaction..."
echo "   - Go to Send tab"
echo "   - Send 50 DD to another address"
echo "   - Check Overview tab"
echo "   - Should show both transactions:"
echo "     📤 Send $50.00 Pending"
echo "     🏦 Mint $100.00 X conf"
echo ""

echo "=========================================="
echo "Manual Testing Instructions"
echo "=========================================="
echo ""
echo "The Qt wallet is running. Please perform these steps:"
echo ""
echo "Step 1: Generate initial blocks"
echo "  ./src/digibyte-cli -regtest -rpcuser=test -rpcpassword=test generatetoaddress 150 \$(./src/digibyte-cli -regtest -rpcuser=test -rpcpassword=test getnewaddress)"
echo ""
echo "Step 2: Navigate to DigiDollar > Overview"
echo "  - Should show 'No recent DigiDollar transactions'"
echo "  - Balance: 0.00 DD"
echo ""
echo "Step 3: Mint some DigiDollars"
echo "  - Go to DigiDollar > Mint"
echo "  - Enter: 100.00 DD, Tier 1 (30 days)"
echo "  - Click 'Mint DigiDollar'"
echo "  - Wait for success message"
echo ""
echo "Step 4: Check Overview tab"
echo "  - Go back to DigiDollar > Overview"
echo "  - Should show: 🏦 Mint \$100.00 Pending"
echo "  - Balance: 100.00 DD"
echo ""
echo "Step 5: Mine a block to confirm"
echo "  ./src/digibyte-cli -regtest -rpcuser=test -rpcpassword=test generatetoaddress 1 \$(./src/digibyte-cli -regtest -rpcuser=test -rpcpassword=test getnewaddress)"
echo ""
echo "Step 6: Check Overview tab again"
echo "  - Should show: 🏦 Mint \$100.00 1 conf"
echo "  - Mine 5 more blocks and it should show 'Confirmed'"
echo ""
echo "Step 7: Send some DigiDollars"
echo "  - Go to DigiDollar > Send"
echo "  - Generate a test address: ./src/digibyte-cli -regtest -rpcuser=test -rpcpassword=test getnewaddress"
echo "  - Convert to DD address format (dgbrt1...)"
echo "  - Send 50.00 DD to that address"
echo ""
echo "Step 8: Check Overview tab"
echo "  - Should show two transactions:"
echo "    📤 Send \$50.00 Pending"
echo "    🏦 Mint \$100.00 X conf"
echo "  - Balance: 50.00 DD"
echo ""
echo "=========================================="
echo ""
echo "Press Ctrl+C when done testing to stop the wallet..."

# Wait for user to finish testing
wait $QT_PID